jwt:
  secret: 4t2mHsym2c/S39GLy8VameEgaiyB4XuPV1j/XfKw1qs=
  hours: 0
  mins: 5
  secs: 0
  
#hours*mins*secs
  
server:
  port: 8082
  ssl:
   enabled: false
   key-store-type: JKS
   key-store-provider: SUN
   key-store: bppra_certificate.jks
   key-alias: bppra_certificate
   key-password: paysys@123
   key-store-password: paysys@123
  
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: WARN
  config: file:logback.xml

debug: true
 
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.0.110.3:1440;databaseName=BEOE_UAT;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=false  

    username : ENC(aF3V2Gker0iesnTTR30h2c7MVmCyi8kV)
    password : ENC(lG2+V+BWsvTE1yGscQoO/IF9dM+xU3ea)
    

    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 8
      maximum-pool-size: 24
      pool-name: sql-pool
      auto-commit: true
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none #none update, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    
springfox.documentation.swagger.v2.path: /docs

swagger:
  enabled: true  
  
  
payment:
  pendingThresholdMinutes: 15
  pendingVoucherUpdateMessage: A Transaction for this voucher has already been made, but marking your voucher to paid for some reason. this will be fixed within a few hours.
  pendingPaymentMessage: A Transaction for this voucher is pending, please wait while that transaction is successful of rejected.	
  log:
    table: payment_log
  
api:
  title: OPEN CONNECT API
  description: REST Services for interacting with the exchange
  version: 1.0
  contact: 033333333
  name: Paysys Labs
  link: http://www.paysyslabs.com/
  email: info@paysyslabs.com
  url-patterns: /api/v1/*


mpay:
   external:
      username: 'INPUTT'
      password: ''
      operand: 'EQ'
      company: 'PK0010001'
      columnName: 'LEGAL.ID'
      criteriaValue: 'ACCOUNT'
      
security:
  login:
    max-attempts: 3
    
    
fbr:
  identification:
   type: 5  
  bank:
   mnemonic: NBP	

uom:
  bank:
   mnemonic: UOM
  reserved:     


bzu:
  username : nbp@361
  password : NBP@791
  
service:
  auth:
    multilogin: true
  customer:
    password:
      min-length: 8
      max-length: 14
    username:
      min-length: 8
      max-length: 14
    registration:
      password-length: 10
    default-package: 1
    count:
      check: false
    allowed:
      count: 1
    rda:
      password-length: 10
      default-package: 1  
  url:
    queue: http://10.0.110.1:7033/nbpl/queueforwarding/
    
  thread-pool:
    notification: 4
    activity-log: 4
    audit-log: 4
    login-audit-log: 4
    balance-inquiry: 4
  timeout:
    connect: 15000
    read: 75000
  concurrency:
    maxtotal: 200
    maxperroute: 100

#simulator key
mpay.calls.simulator: 0 

slic:
   billerIdLoan: 1701
   billerIdPremium: 1702
  
bppra:  
   tenderPrefix: 337
   supplierPrefix: 787 
   authticateCall: https://bppdev.vdc.services:7443/api/Aouth/authenticate
   tokenInquiryCall: https://bppdev.vdc.services:7443/api/Aouth/Inititate-Enquery
   tenderChallanInquiryCall: https://bppdev.vdc.services:7443/api/ChallanEnquire/RequestChallanByChallanCode
   tenderChallanPaidCall: https://bppdev.vdc.services:7443/api/ChallanEnquire/MarkChallanPaid   
   supplierChallanInquiryCall: https://bppdev.vdc.services:7443/api/ChallanEnquire/RequestSupplierChallanByChallanCode
   supplierChallanPaidCall: https://bppdev.vdc.services:7443/api/ChallanEnquire/MarkSupplierChallanPaid   
   completeInquiryCall: https://bppdev.vdc.services:7443/api/Aouth/Complete-Enquery  
   clientSecret: Gsz-mtdhh3aSCscvUsLxUne2piVaoVxRnlhiZZEIJV4bUOiIh_m2SidXkKIh0NDORxL3tJDRsu3eQdfTVpat2dwPjfEi0PP80_a-DYDPrTCNMtKPbMM7B4svjBugW5fd
   requestFormAuth: client
   requestFormChallanEnquire: enquirer
   branchCode: 9211
   personName: Ali
   

bise:
  kohat:
     username: nbpapitest
     password: nbpapitest
   
   

