jwt:
  secret: 4t2mHsym2c/S39GLy8VameEgaiyB4XuPV1j/XfKw1qs=
  hours: 0
  mins: 5
  secs: 0
  
#hours*mins*secs
  
server:
  port: 8082 
  
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: WARN
  config: file:logback.xml

debug: true
 
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.0.110.3:1440;databaseName=BEOE_UAT;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=false  

    username : ENC(aF3V2Gker0iesnTTR30h2c7MVmCyi8kV)
    password : ENC(lG2+V+BWsvTE1yGscQoO/IF9dM+xU3ea)
    

    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 8
      maximum-pool-size: 24
      pool-name: sql-pool
      auto-commit: true
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none #none update, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    
springfox.documentation.swagger.v2.path: /docs

swagger:
  enabled: true  
  
  
payment:
  pendingThresholdMinutes: 15
  pendingVoucherUpdateMessage: A Transaction for this voucher has already been made, but marking your voucher to paid for some reason. this will be fixed within a few hours.
  pendingPaymentMessage: A Transaction for this voucher is pending, please wait while that transaction is successful of rejected.	
  log:
    table: payment_log
  
api:
  title: OPEN CONNECT API
  description: REST Services for interacting with the exchange
  version: 1.0
  contact: 033333333
  name: Paysys Labs
  link: http://www.paysyslabs.com/
  email: info@paysyslabs.com
  url-patterns: /api/v1/*


mpay:
   external:
      username: 'INPUTT'
      password: ''
      operand: 'EQ'
      company: 'PK0010001'
      columnName: 'LEGAL.ID'
      criteriaValue: 'ACCOUNT'
      
security:
  login:
    max-attempts: 3
    
    
fbr:
  identification:
   type: 5  
  bank:
   mnemonic: NBP	

uom:
  bank:
   mnemonic: UOM
  reserved:     


bzu:
  username : nbp@361
  password : NBP@791
  
service:
  auth:
    multilogin: true
  customer:
    password:
      min-length: 8
      max-length: 14
    username:
      min-length: 8
      max-length: 14
    registration:
      password-length: 10
    default-package: 1
    count:
      check: false
    allowed:
      count: 1
    rda:
      password-length: 10
      default-package: 1  
  url:
    queue: http://10.0.110.1:7033/nbpl/queueforwarding/
    
  thread-pool:
    notification: 4
    activity-log: 4
    audit-log: 4
    login-audit-log: 4
    balance-inquiry: 4
  timeout:
    connect: 15000
    read: 75000
  concurrency:
    maxtotal: 200
    maxperroute: 100

#simulator key
mpay.calls.simulator: 0 

slic:
  billerid-1: 1701
  billerid-2: 1702
  
bppra:  
   authticateCall: https://bppdev.vdc.services:7443/api/Aouth/authenticate
   initiateInquiryCall: https://bppdev.vdc.services:7443/api/Aouth/Inititate-Enquery
   challanInquiryCall: https://bppdev.vdc.services:7443/api/ChallanEnquire/RequestChallanByChallanCode?
   tenderChallanPaid: https://bppdev.vdc.services:7443/api/ChallanEnquire/MarkChallanPaid     
   clientSecret: Gsz-mtdhh3aSCscvUsLxUne2piVaoVxRnlhiZZEIJV4bUOiIh_m2SidXkKIh0NDORxL3tJDRsu3eQdfTVpat2dwPjfEi0PP80_a-DYDPrTCNMtKPbMM7B4svjBugW5fd
   requestFormAuth: client
   requestFormChallanEnquire: enquirer
   publicKey: -----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwR1lerIclVf4qXmQ9B/I Y2IpH+oIah3N+3QnT4ll4qPc1VS1PtHWvaSdlX0c90nTH5SqqzXS8Bze9HpSZZss 3RtDrSMW9w6mYtFN3MqxjoOuYbZ1519rC+tOLEsqwyvECoMn8a7k7f96kfg3qpy5 nc8oASvJOh8CRM5sEeKhM6ixMMVFjP7JO2222ZQI3aTWcnZ00svmvT3ZgMPJ6LeZ wyeKh9GoLuLtuAbF4P0gDLFsAdvH8UrLclLfDBoP3F3zQGGYYFRAiXGkvC9Q192m eEA9O1BEx5ZnZiqCpx66QC0ZPQnEk54c8G+scmqibjoOHRHuIqknUffT8wyZeEBw kwIDAQAB -----END PUBLIC KEY-----
   privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDBHWV6shyVV/ipeZD0H8hjYikf6ghqHc37dCdPiWXio9zVVLU+0da9pJ2VfRz3SdMflKqrNdLwHN70elJlmyzdG0OtIxb3DqZi0U3cyrGOg65htnXnX2sL604sSyrDK8QKgyfxruTt/3qR+DeqnLmdzygBK8k6HwJEzmwR4qEzqLEwxUWM/sk7bbbZlAjdpNZydnTSy+a9PdmAw8not5nDJ4qH0agu4u24BsXg/SAMsWwB28fxSstyUt8MGg/cXfNAYZhgVECJcaS8L1DX3aZ4QD07UETHlmdmKoKnHrpALRk9CcSTnhzwb6xyaqJuOg4dEe4iqSdR99PzDJl4QHCTAgMBAAECggEAMxSKfhzUsLAXRwSv0dMCVz9kr1thJGiDzopXx5MJTxyW0hrY4ifxDDKZuCvi2Io/fO//ANB43ihU1Qfx+YxFHqsSiJ5qeaj3W9YPKWK3+oFcQ95Wa3/yubFg+Rhc1EkkTr+IdkYTqdxU2H12g/t2oYZlB4JEdMo0+Gw9a7GtgBMeM9iHB5QAJ6YabdpbX0jXYCfHNUPr5tuZbdBh+M0fxwvpPI3K9jpinrkShuLFn8xZECkIvYJ+/GdPOFc/L+TChFb4HqvuvN1ylfir+WuUng2+3fdkhGRqQlrb8GabYUEsBOYpAY6qZ3F3rY7VP6ixW0hvOEjYcpL/K4e/81g3aQKBgQDljUdPJ5E8BuR1P1u/wcaYHNn8iv7gglGRM0CJUFS0qKZ5WQXsG0wtZUsFGIfyaVpptKMkKPnyPiU2DkAif5ebYzy3YzjHPB4zW/vI77TBA5Ni/PAS6XJc11oiGQOWZdtexXZYjQXz2OqvEa0wKFjYGIltl4Z3ihIcNpQ3xbgkhQKBgQDXXWSqxMiCrlKOHXbtZCsOTz53pRKMeQsztdmeHfl5R/5eKRhT46mF/R07T+sfCf3Ir1ZPTXV65eeT4PkrB9xTkJ/2NyEYJcovJpaYGxXy2waJ4ajcLF3r43YY4hFWY+rlZWTgD4TcC+28bb4wCDXQyOOcsfHABO0XM8ubHP24NwKBgEbAzQHwyCsgVLpu1PC94WBxRB87GGRKxqliirnIMNOeR/GPJuwnXcuANSdU8FIfduat7rruhlvMG9wVeF8pxKj4ZXaA9rcyKHzcFTdR6vyzBXK1U6oAmmdTWUy5OQnaS0tiwZ95mCQY7/0WDbOSPBAfP/yvf5rIy9w2Vmj6YE+hAoGAZM2G99NBksErTO+HodeXu4vlzjSKeQuS7bI5WKPpCBZlfgc4JtPRnjB6BTAD+jRAADXpbRbxXQPNH89WcQit3MM9zA3DxLyzZNxn8mwDGvffmJvx4JQ3pdiCh2UQ/mGoKZUK4UECS8idjuvC8FJ3dfEBcG9tmxXzL0AEFec87oMCgYBd1QPx1rtNkf99uywYo+mb2DSqOxbtiM9PwHe5ks0fWuAcwJkjzX/bqT4nwN+h6LspN/3Ni6DmgnhMj8M/qzE7ObJ99shIoCMPqUjPavKberZzQdDREgfu6CzON1sNXIRR5m3039hxSLc8CRo0Br0/SVUrHH8lFzFXhe6InyGB9A==
   